### ISSUE TITLE
ModuleNotFoundError: No module named 'openapi_client.exceptions'

### ISSUE THREAD

**Issue by moayadeldin** [namsor/namsor-python-sdk2#2]
Hello,

After following the Installation Procedure mentioned in the Readme file, whenever I run the code snippet in Getting started section I get the following error when I import openapi_client:
ModuleNotFoundError: No module named 'openapi_client.exceptions'

It seems to occur in the rest.py file mainly when it try to import the following line:
from openapi_client.exceptions import ApiException, ApiValueError

How may this be solved? I tried to look in the source code but didn't find the following 'openapi_client.exceptions' directory.

Thank you,

**Comment by namsor** [comment]
Thanks for reporting this, it should now be OK.
